# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VladyslavFedoniuk.Snoq
PackageVersion: 2026.10.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
ExpectedReturnCodes:
- InstallerReturnCode: 32
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: SNOQ
ElevationRequirement: elevationProhibited
Installers:
- Architecture: x64
  InstallerUrl: https://snoq.io/releases/SNOQ-Setup-2026.10.1.exe
  InstallerSha256: D6F55FFE95B7EC6222C35A23D0DA2BA801F11BF12D8CD2F91EE11BA1D034492B
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
