# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VladyslavFedoniuk.FTPie
PackageVersion: 2026.10.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
ExpectedReturnCodes:
- InstallerReturnCode: 32
  ReturnResponse: packageInUse
UpgradeBehavior: install
Commands:
- ftpie-cli
ProductCode: FTPie
ElevationRequirement: elevationProhibited
Installers:
- Architecture: x64
  InstallerUrl: https://ftpie.com/releases/FTPie-Setup-2026.10.1.exe
  InstallerSha256: ECD6CDE1DD6614C1303EC916911D4408DA903D6855EE356AB62C2B486D089A30
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
