# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VladyslavFedoniuk.RSSly
PackageVersion: 2026.10.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
ExpectedReturnCodes:
- InstallerReturnCode: 32
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: RSSly
ElevationRequirement: elevationProhibited
Installers:
- Architecture: x64
  InstallerUrl: https://rssly.io/releases/RSSly-Setup-2026.10.1.exe
  InstallerSha256: 47936297582AF3D1529B54E17A6267C1443D8F29963E98CABDBCE21A2D73DB7E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
