# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VladyslavFedoniuk.BackupKit
PackageVersion: 2026.10.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
ExpectedReturnCodes:
- InstallerReturnCode: 32
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: BackupKit
ElevationRequirement: elevationProhibited
Installers:
- Architecture: x64
  InstallerUrl: https://backupkit.io/releases/BackupKit-Setup-2026.10.1.exe
  InstallerSha256: A27B43459A94CB172AD3A63188C62736B76AA69E21A3C59E3E6351ED3033E897
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
