# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VladyslavFedoniuk.TabChart
PackageVersion: 2026.10.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
ExpectedReturnCodes:
- InstallerReturnCode: 32
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: TabChart
ElevationRequirement: elevationProhibited
Installers:
- Architecture: x64
  InstallerUrl: https://tabchart.com/releases/TabChart-Setup-2026.10.1.exe
  InstallerSha256: EAFB22D726468702477B835501DADCDA075767B57E01A6F372E95E876B4F5849
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
